pi_serial: pi_serial.c
	gcc -lpthread -o pi_serial pi_serial.c
pi_multi-thread:
	gcc -lpthread -o pi_multi-thread pi_multi-thread.c
code:
	gcc -lpthread -o code code.c 
clean:
	rm -r -f *.o code pi_multi-thread pi_serial